stages:
  - install
  - build
  - test

install_packages:
  stage: install
  script:
    - apt -y update
    - apt -y upgrade
    - apt -y install python3.7
    - apt -y install software-properties-common
    - apt -y install python3-pip
    - apt -y install git-all
    - python3 --version
    - pip3 install ansible
    - ansible --version

ui_installation:
  stage: build
  script:
    - pwd
    - ls -a
    - ansible --version
    - ./setup.sh CI

ui_test:
  stage: test
  script:
    - echo "Tests will be here."