stages:
  - build
  - test

build-job:
  stage: build
  script:
    - ls
    - cat /etc/os-release

build-job1:
  stage: test
  script:
    - apt-get update
    - apt-get upgrade
    - apt-get install software-properties-common
    - apt install python3

