stages:
  - build
  - test

install_packages:
  stage: build
  script:
    - apt -y update
    - apt -y upgrade
    - apt -y install python3.7
    - apt -y install software-properties-common
    - apt -y install python3-pip
    - python3 --version
    - pip install ansible

