stages:
  - runner-setup
  - build
  - test

create_pi:
  stage: runner-setup
  script:
    - groupadd pi
    - useradd -u 1000 -g pi -m -p raspberry pi
    - usermod -aG sudo pi

install_packages:
  stage: build
  dependencies: runner-setup
  script:
    - apt -y autoremove
    - apt -y update
    - apt -y upgrade
    - apt -y install python3.7 software-properties-common python3-pip git-all raspi-config
    - python3 --version
    - pip3 install ansible
    - ansible --version
    - ls
    - pwd
    - ./setup.sh CI

ui_installation:
  stage: build
  dependencies: build
  script:
    - pwd
    - ls -a

ui_test:
  stage: test
  script:
    - echo "Tests will be here."