stages:
  - build
  - test

install_packages:
  stage: build
  script:
    - apt -y update
    - apt -y upgrade
    - apt -y install software-properties-common
    - apt -y install python3-pip
    - alias python=python3
    - python --version
    - pip install ansible

