stages:
  - build
  - test

build-job:
  stage: build
  script:
    - ls
    - cat /etc/os-release

build-job1:
  stage: test
  script:
    - apt -y update
    - apt -y upgrade
    - apt -y install software-properties-common
    - apt -y install python3

