stages:
  - build
  - test

build-job:
  stage: build
  script:
    - ls
    - cat /etc/os-release

build-job1:
  stage: test
  script:
    - sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
    - sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.7 2
    - pip3 install ansible

