stages:
  - build
  - test

before_script:
  - pwd
  - echo 'test'
  - groupadd pi
  - useradd -u 1000 -g pi -m -p raspberry pi
  - usermod -aG sudo pi
  - mkdir -p /home/pi/Downloads
  - apt -y autoremove
  - apt -y update
  - apt -y upgrade
  - apt -y install python3.7 software-properties-common python3-pip git-all raspi-config
  - python3 --version
  - pip3 install ansible
  - ansible --version

# install_packages:
#   stage: install
#   script:
#     - apt -y autoremove
#     - apt -y update
#     - apt -y upgrade
#     - apt -y install python3.7 software-properties-common python3-pip git-all raspi-config
#     - python3 --version
#     - pip3 install ansible
#     - ansible --version

ui_installation:
  stage: build
  script:
    - ls -a
    - pwd
    - cd /home/pi/hev
    - ./setup.sh CI

ui_test:
  stage: test
  script:
    - echo "Tests will be here."