rpi_swlist:
# © Copyright CERN, Riga Technical University and University of Liverpool 2020.
# All rights not expressly granted are reserved. 
# 
# This file is part of hev-sw.
# 
# hev-sw is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public Licence as published by the Free
# Software Foundation, either version 3 of the Licence, or (at your option)
# any later version.
# 
# hev-sw is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public Licence
# for more details.
# 
# You should have received a copy of the GNU General Public License along
# with hev-sw. If not, see <http://www.gnu.org/licenses/>.
# 
# The authors would like to acknowledge the much appreciated support
# of all those involved with the High Energy Ventilator project
# (https://hev.web.cern.ch/).


  - vim
  - emacs
  - cowsay
  - openssh-server
  - minicom
  - python3
  - sqlite3
  - cmake
  - libts0
  - libglvnd-dev  
  - libfontconfig1-dev 
  - libdbus-1-dev 
  - libicu-dev 
  - libinput-dev
  - libxkbcommon-dev 
  - libsqlite3-dev 
  - libssl-dev 
  - libjpeg-dev 
  - libglib2.0-dev
  - socat
  - apache2
  - libapache2-mod-wsgi-py3 
  - lxappearance
  - libatlas-base-dev
  - python3-pyside2.qt3dcore
  - python3-pyside2.qt3dinput
  - python3-pyside2.qt3dlogic
  - python3-pyside2.qt3drender
  - python3-pyside2.qtcharts
  - python3-pyside2.qtconcurrent
  - python3-pyside2.qtcore
  - python3-pyside2.qtgui
  - python3-pyside2.qthelp
  - python3-pyside2.qtlocation
  - python3-pyside2.qtmultimedia
  - python3-pyside2.qtmultimediawidgets
  - python3-pyside2.qtnetwork
  - python3-pyside2.qtopengl
  - python3-pyside2.qtpositioning
  - python3-pyside2.qtprintsupport
  - python3-pyside2.qtqml
  - python3-pyside2.qtquick
  - python3-pyside2.qtquickwidgets
  - python3-pyside2.qtscript
  - python3-pyside2.qtscripttools
  - python3-pyside2.qtsensors
  - python3-pyside2.qtsql
  - python3-pyside2.qtsvg
  - python3-pyside2.qttest
  - python3-pyside2.qttexttospeech
  - python3-pyside2.qtuitools
  - python3-pyside2.qtwebchannel
  - python3-pyside2.qtwebsockets
  - python3-pyside2.qtwidgets
  - python3-pyside2.qtx11extras
  - python3-pyside2.qtxml
  - python3-pyside2.qtxmlpatterns
  - python3-pyside2uic

pip_list: 
  - virtualenv
  